name: Compatible Jasmine Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jasmine-version: [2.x, 3.x, 4.x, 5.x]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node.js 22.x
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm install jasmine@${{ matrix.jasmine-version }} jasmine-core@${{ matrix.jasmine-version }} @types/jasmine@${{ matrix.jasmine-version }}
    - run: npm test
